# Generated by Django 2.2.3 on 2019-07-25 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casenumber', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('investigator', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
